// <auto-generated />
using System;
using MesaDeAyuda.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MesaDeAyuda.Migrations
{
    [DbContext(typeof(MesaAyudaDbContext))]
    [Migration("20260928003909_AddTableTipoValidacionCierre")]
    partial class AddTableTipoValidacionCierre
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.Caso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaHoraCaducidad")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaHoraFinCaso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaHoraIngreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumeroCaso")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroCliente")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroIteracion")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoCasoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("TipoCasoId");

                    b.ToTable("Caso");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstadoId = 1,
                            FechaHoraCaducidad = new DateTime(2026, 9, 16, 12, 0, 0, 0, DateTimeKind.Utc),
                            FechaHoraIngreso = new DateTime(2026, 9, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            NumeroCaso = 1001,
                            NumeroCliente = 5001,
                            NumeroIteracion = 1,
                            Observaciones = "Cliente reporta caída intermitente de conexión.",
                            TipoCasoId = 1
                        },
                        new
                        {
                            Id = 2,
                            EstadoId = 1,
                            FechaHoraCaducidad = new DateTime(2026, 9, 16, 12, 0, 0, 0, DateTimeKind.Utc),
                            FechaHoraIngreso = new DateTime(2026, 9, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            NumeroCaso = 1002,
                            NumeroCliente = 5002,
                            NumeroIteracion = 1,
                            Observaciones = "Reclamo por corte total del servicio.",
                            TipoCasoId = 1
                        },
                        new
                        {
                            Id = 3,
                            EstadoId = 2,
                            FechaHoraCaducidad = new DateTime(2026, 9, 16, 12, 0, 0, 0, DateTimeKind.Utc),
                            FechaHoraIngreso = new DateTime(2026, 9, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            NumeroCaso = 1003,
                            NumeroCliente = 5003,
                            NumeroIteracion = 1,
                            Observaciones = "Consulta por lentitud de conexión.",
                            TipoCasoId = 1
                        });
                });

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.CasoInstancia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CasoId")
                        .HasColumnType("integer");

                    b.Property<int?>("EspecialistaId")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaHoraFinPlanificada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaHoraFinReal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaHoraInicioPlanificada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaHoraInicioReal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrdenCasoInstancia")
                        .HasColumnType("integer");

                    b.Property<int>("TipoInstanciaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CasoId");

                    b.HasIndex("EspecialistaId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("TipoInstanciaId");

                    b.ToTable("CasoInstancia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CasoId = 1,
                            EspecialistaId = 1,
                            EstadoId = 1,
                            FechaHoraFinPlanificada = new DateTime(2026, 9, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            FechaHoraInicioPlanificada = new DateTime(2026, 9, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            FechaHoraInicioReal = new DateTime(2026, 9, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Observaciones = "",
                            OrdenCasoInstancia = 1,
                            TipoInstanciaId = 1
                        },
                        new
                        {
                            Id = 2,
                            CasoId = 1,
                            EstadoId = 6,
                            FechaHoraFinPlanificada = new DateTime(2026, 9, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            Observaciones = "",
                            OrdenCasoInstancia = 2,
                            TipoInstanciaId = 2
                        },
                        new
                        {
                            Id = 3,
                            CasoId = 1,
                            EstadoId = 6,
                            FechaHoraFinPlanificada = new DateTime(2026, 9, 13, 12, 0, 0, 0, DateTimeKind.Utc),
                            Observaciones = "",
                            OrdenCasoInstancia = 3,
                            TipoInstanciaId = 3
                        },
                        new
                        {
                            Id = 4,
                            CasoId = 2,
                            EspecialistaId = 1,
                            EstadoId = 4,
                            FechaHoraFinPlanificada = new DateTime(2026, 9, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            FechaHoraFinReal = new DateTime(2026, 9, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            FechaHoraInicioPlanificada = new DateTime(2026, 9, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            FechaHoraInicioReal = new DateTime(2026, 9, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Observaciones = "No se logró restablecer el servicio en el primer contacto.",
                            OrdenCasoInstancia = 1,
                            TipoInstanciaId = 1
                        },
                        new
                        {
                            Id = 5,
                            CasoId = 2,
                            EspecialistaId = 2,
                            EstadoId = 4,
                            FechaHoraFinPlanificada = new DateTime(2026, 9, 13, 12, 0, 0, 0, DateTimeKind.Utc),
                            FechaHoraFinReal = new DateTime(2026, 9, 13, 12, 0, 0, 0, DateTimeKind.Utc),
                            FechaHoraInicioPlanificada = new DateTime(2026, 9, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            FechaHoraInicioReal = new DateTime(2026, 9, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Observaciones = "Se descarta falla en el domicilio del cliente.",
                            OrdenCasoInstancia = 2,
                            TipoInstanciaId = 2
                        },
                        new
                        {
                            Id = 6,
                            CasoId = 2,
                            EspecialistaId = 3,
                            EstadoId = 1,
                            FechaHoraFinPlanificada = new DateTime(2026, 9, 16, 12, 0, 0, 0, DateTimeKind.Utc),
                            FechaHoraInicioPlanificada = new DateTime(2026, 9, 13, 12, 0, 0, 0, DateTimeKind.Utc),
                            FechaHoraInicioReal = new DateTime(2026, 9, 13, 12, 0, 0, 0, DateTimeKind.Utc),
                            Observaciones = "",
                            OrdenCasoInstancia = 3,
                            TipoInstanciaId = 3
                        },
                        new
                        {
                            Id = 7,
                            CasoId = 3,
                            EstadoId = 5,
                            FechaHoraFinPlanificada = new DateTime(2026, 9, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Observaciones = "",
                            OrdenCasoInstancia = 1,
                            TipoInstanciaId = 1
                        },
                        new
                        {
                            Id = 8,
                            CasoId = 3,
                            EstadoId = 6,
                            FechaHoraFinPlanificada = new DateTime(2026, 9, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            Observaciones = "",
                            OrdenCasoInstancia = 2,
                            TipoInstanciaId = 2
                        },
                        new
                        {
                            Id = 9,
                            CasoId = 3,
                            EstadoId = 6,
                            FechaHoraFinPlanificada = new DateTime(2026, 9, 13, 12, 0, 0, 0, DateTimeKind.Utc),
                            Observaciones = "",
                            OrdenCasoInstancia = 3,
                            TipoInstanciaId = 3
                        });
                });

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.CasoInstanciaTarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CasoInstanciaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaHoraFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaHoraInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoTareaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CasoInstanciaId");

                    b.HasIndex("TipoTareaId");

                    b.ToTable("CasoInstanciaTarea");
                });

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.Especialista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cuit")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaHoraBaja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Legajo")
                        .HasColumnType("integer");

                    b.Property<string>("NombreApellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SectorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("Especialista");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cuit = 201111116,
                            Legajo = 1001,
                            NombreApellido = "Juan Pérez",
                            SectorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cuit = 272222223,
                            Legajo = 1002,
                            NombreApellido = "Ana Gómez",
                            SectorId = 2
                        },
                        new
                        {
                            Id = 3,
                            Cuit = 203333334,
                            Legajo = 1003,
                            NombreApellido = "Carlos López",
                            SectorId = 3
                        });
                });

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.EstadoCaso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaHoraBaja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EstadoCaso");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Tomado"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Disponible"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Cerrado"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Terminado Sin Éxito en la Iteración"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Terminado Sin Solución"
                        });
                });

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.EstadoCasoInstancia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaHoraBaja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EstadoCasoInstancia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Asignada"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Resuelto"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Cancelada"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Sin Resolver"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "A Asignar"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Sin Asignar"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Caducada"
                        });
                });

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaHoraBaja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sector");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Atención primaria vía telefónica.",
                            Nombre = "Atención Telefónica"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Soporte técnico de segundo nivel.",
                            Nombre = "Soporte Técnico"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Especialistas en infraestructura de red.",
                            Nombre = "Redes"
                        });
                });

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.TipoCaso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaHoraBaja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumeroMaximaIteracion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TipoCaso");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Falla de Conexión",
                            NumeroMaximaIteracion = 3
                        });
                });

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.TipoCasoIteracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoeficienteReduccionTipo")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroDeIteracion")
                        .HasColumnType("integer");

                    b.Property<int>("TipoCasoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoCasoId");

                    b.ToTable("TipoCasoIteracion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoeficienteReduccionTipo = 75,
                            NumeroDeIteracion = 2,
                            TipoCasoId = 1
                        },
                        new
                        {
                            Id = 2,
                            CoeficienteReduccionTipo = 50,
                            NumeroDeIteracion = 3,
                            TipoCasoId = 1
                        });
                });

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.TipoCasoTipoInstancia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaHoraVerificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MinutosMaximaResolucion")
                        .HasColumnType("integer");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("TipoCasoId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoInstanciaId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoValidacionCierreId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoCasoId");

                    b.HasIndex("TipoInstanciaId");

                    b.HasIndex("TipoValidacionCierreId");

                    b.ToTable("TipoCasoTipoInstancia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaAlta = new DateTime(2025, 9, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            MinutosMaximaResolucion = 1440,
                            Orden = 1,
                            TipoCasoId = 1,
                            TipoInstanciaId = 1,
                            TipoValidacionCierreId = 1
                        },
                        new
                        {
                            Id = 2,
                            FechaAlta = new DateTime(2025, 9, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            MinutosMaximaResolucion = 2880,
                            Orden = 2,
                            TipoCasoId = 1,
                            TipoInstanciaId = 2,
                            TipoValidacionCierreId = 3
                        },
                        new
                        {
                            Id = 3,
                            FechaAlta = new DateTime(2025, 9, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            MinutosMaximaResolucion = 4320,
                            Orden = 3,
                            TipoCasoId = 1,
                            TipoInstanciaId = 3,
                            TipoValidacionCierreId = 2
                        });
                });

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.TipoInstancia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaHoraBaja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SectorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("TipoInstancia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Atención Telefónica",
                            SectorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Soporte Técnico",
                            SectorId = 2
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Redes",
                            SectorId = 3
                        });
                });

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.TipoTarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaHoraBaja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TipoTarea");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Contacto telefónico realizado hacia el cliente.",
                            Nombre = "Llamada Saliente"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Revisión técnica del problema reportado.",
                            Nombre = "Diagnóstico Técnico"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Derivación del caso a otro sector o especialista.",
                            Nombre = "Derivación Interna"
                        });
                });

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.TipoValidacionCierre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaHoraBaja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TipoValidacionCierre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Simple"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "PorObservaciones"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "PorTareaRegistrada"
                        });
                });

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.Caso", b =>
                {
                    b.HasOne("MesaDeAyuda.Domain.Entities.EstadoCaso", "EstadoActual")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MesaDeAyuda.Domain.Entities.TipoCaso", "TipoCaso")
                        .WithMany()
                        .HasForeignKey("TipoCasoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoActual");

                    b.Navigation("TipoCaso");
                });

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.CasoInstancia", b =>
                {
                    b.HasOne("MesaDeAyuda.Domain.Entities.Caso", "Caso")
                        .WithMany("Instancias")
                        .HasForeignKey("CasoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MesaDeAyuda.Domain.Entities.Especialista", "Especialista")
                        .WithMany()
                        .HasForeignKey("EspecialistaId");

                    b.HasOne("MesaDeAyuda.Domain.Entities.EstadoCasoInstancia", "EstadoActual")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MesaDeAyuda.Domain.Entities.TipoInstancia", "TipoInstancia")
                        .WithMany()
                        .HasForeignKey("TipoInstanciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caso");

                    b.Navigation("Especialista");

                    b.Navigation("EstadoActual");

                    b.Navigation("TipoInstancia");
                });

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.CasoInstanciaTarea", b =>
                {
                    b.HasOne("MesaDeAyuda.Domain.Entities.CasoInstancia", "CasoInstancia")
                        .WithMany("Tareas")
                        .HasForeignKey("CasoInstanciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MesaDeAyuda.Domain.Entities.TipoTarea", "TipoTarea")
                        .WithMany()
                        .HasForeignKey("TipoTareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CasoInstancia");

                    b.Navigation("TipoTarea");
                });

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.Especialista", b =>
                {
                    b.HasOne("MesaDeAyuda.Domain.Entities.Sector", "Sector")
                        .WithMany("Especialistas")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.TipoCasoIteracion", b =>
                {
                    b.HasOne("MesaDeAyuda.Domain.Entities.TipoCaso", "TipoCaso")
                        .WithMany("TiposCasoIteracion")
                        .HasForeignKey("TipoCasoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoCaso");
                });

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.TipoCasoTipoInstancia", b =>
                {
                    b.HasOne("MesaDeAyuda.Domain.Entities.TipoCaso", "TipoCaso")
                        .WithMany("TiposCasoTipoInstancia")
                        .HasForeignKey("TipoCasoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MesaDeAyuda.Domain.Entities.TipoInstancia", "TipoInstancia")
                        .WithMany("TiposCasoTipoInstancia")
                        .HasForeignKey("TipoInstanciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MesaDeAyuda.Domain.Entities.TipoValidacionCierre", "TipoValidacionCierre")
                        .WithMany()
                        .HasForeignKey("TipoValidacionCierreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoCaso");

                    b.Navigation("TipoInstancia");

                    b.Navigation("TipoValidacionCierre");
                });

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.TipoInstancia", b =>
                {
                    b.HasOne("MesaDeAyuda.Domain.Entities.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.Caso", b =>
                {
                    b.Navigation("Instancias");
                });

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.CasoInstancia", b =>
                {
                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.Sector", b =>
                {
                    b.Navigation("Especialistas");
                });

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.TipoCaso", b =>
                {
                    b.Navigation("TiposCasoIteracion");

                    b.Navigation("TiposCasoTipoInstancia");
                });

            modelBuilder.Entity("MesaDeAyuda.Domain.Entities.TipoInstancia", b =>
                {
                    b.Navigation("TiposCasoTipoInstancia");
                });
#pragma warning restore 612, 618
        }
    }
}
